services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/tododb
    ports:
      - "9000:8000"
    depends_on:
      - db
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"

  frontend:
    build: .
    environment:
      REACT_APP_API_URL: http://localhost:9000
    ports:
      - "9001:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true

volumes:
  db_data: